#!/bin/bash

# Copy $HOME/.cache/winetricks to snap location.
if [[ -d "${SNAP_REAL_HOME}/.cache/winetricks" ]]; then
    mkdir -p "${SNAP_USER_COMMON}/.cache/winetricks"
    cp -r "${SNAP_REAL_HOME}/.cache/winetricks/" "${SNAP_USER_COMMON}/.cache/winetricks"
fi
