name: cardsorter
base: core20
version: '20210306'
summary: Sort word list cards virtually.
description: |
  Sort word list cards virtually.

grade: devmode # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

license: GPL-3.0+
contact: https://github.com/n8marti/cardsorter-snap

apps:
  cardsorter:
    # command needs to exist in the snap; hence wrapper for xdg-open
    command: bin/run_app.sh $SNAP/cardsorter/index.html
    # command-chain:
    #   - run_app.sh
    # extensions:
      # - gnome-3-38
    plugs:
      - desktop
      - desktop-legacy
      # - home
      # - removable-media

parts:
  site:
    plugin: dump
    source: http://casali.canil.ca/CardSorter/CardSorter.zip
    organize:
      "*": cardsorter/
  launcher:
    plugin: dump
    # source has to be a directory, whether compressed or not
    source: .
    organize:
      run_app.sh: bin/
