name: cardsorter
base: core20
version: '20210306'
summary: Sort word list cards virtually.
description: |
  Sort word list cards virtually.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

license: GPL-3.0+
contact: https://github.com/n8marti/cardsorter-snap

apps:
  cardsorter:
    command: xdg-open $SNAP/index.html
    extensions:
      - gnome-3-38
    plugs:
      - home
      - removable-media

parts:
  site:
    plugin: dump
    source: http://casali.canil.ca/CardSorter/CardSorter.zip
