name: cardsorter
base: core20
version: '20210306'
summary: Sort word list cards virtually.
description: |
  Sort word list cards virtually.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

apps:
  cardsorter:
    # extensions: [gnome-3-28]
    command: desktop-launch $SNAP/nw
    plugs:
      - audio-playback
      - desktop
      - home
      - network
      - network-bind
      - opengl
      # - process-control
      # - system-observe
      # - system-trace
      - udisks2

parts:
  metadata:
    plugin: dump
    source: metadata/
  nwjs:
    plugin: dump
    source: https://dl.nwjs.io/v0.64.0/nwjs-v0.64.0-linux-x64.tar.gz
  site:
    plugin: dump
    source: http://casali.canil.ca/CardSorter/CardSorter.zip
    after:
      - nwjs-support
      - desktop-gtk3
